### ISSUE TITLE
Are you sure AMSI supports standalone office?

### ISSUE THREAD

**Issue by subvert0r** [manyfacedllama/amsi-tracer#3]
I tried your project with Office 2016 and set that registry key, but only 5% of document files that have a macro generate a file in the logs folder for word or excel. (My test files execute a powershell command using office macros for word or excel)

**Comment by 10sor** [comment]
AFAIK only specific macro calls intercepted

from: https://blogs.blackberry.com/en/2018/04/how-to-implement-anti-malware-scanning-interface-provider

A limitation to AMSI callbacks is that it is opt-in by the scripting engine and in the case of VBE7.dll (Office’s Macro engine), the callbacks are executed on a subset of commands such as “Shell”. An attacker could easily bypass the AMSI callback by running CreateObject(“WScript.Shell”).Run(sCmd).

**Comment by manyfacedllama** [comment]
Are all your test files executing the same macro?

If you are testing across different types of macro implementations, you need to keep in mind that not everything is passed into AMSI as @10sor has pointed out. You can read my previous answer to a similar question here: https://twitter.com/mkazemhn/status/1318382560389427200
